name: deploy
permissions:
  contents: write

on:
  # 每当 push 到 wiki 分支时触发部署
  # Deployment is triggered whenever a push is made to the main branch.
  push:
    branches: [wiki]
  # 手动触发部署
  # Manually trigger deployment
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          # "Last updated time" and other git log-related information require fetching all commit records.
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # 选择要使用的 node 版本
          node-version: 20

      # 安装依赖
      # Install dependencies
      - name: Install Dependencies
        run: npm ci



      # 运行构建脚本
      # Run the build script
      - name: Build VuePress site
        run: npm run docs:build


      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          repo: TartaricAcid/TouhouLittleMaid
          # 部署到 gh-pages 分支
          target_branch: gh_pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
          # 部署 CNAME
          # fqdn: ysm.cfpa.team
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}